### ISSUE TITLE
Contributing file and Code of conduct file 

### ISSUE THREAD

**Issue by akrish4** [Upasthiti-Dev/Upasthiti-The-Real-Checker#3]
Hi @Apoorve73 
I noticed in this repository there is no contributing file and code  of conduct file , I would like to work on this , Let me know whether I can work on this if yes , kindly  assign this issue to me

**Comment by Apoorve73** [comment]
Hello,

We are working on updating that. I will look into it and assign if possible.

Best,
Apoorve

**Comment by akrish4** [comment]
ok sure @Apoorve73

**Comment by Sloth-Panda** [comment]
Hey, can you give me this issue

**Comment by Apoorve73** [comment]
We are working on updating the README and CONTRIBUTIONS file. Once done, we will ourselves open issue to work upon the project.

Till then you can read the blog,using link provided in description to know about its working. :)

**Comment by Apoorve73** [comment]
@akrish4 and @Sloth-Panda , try to play around with this project on your own system. May be you find some bugs 👍
